# Generated by Django 4.2.4 on 2023-08-18 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='Role',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
