# Generated by Django 4.2.4 on 2023-08-31 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0002_profile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pooja',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=25)),
                ('description', models.TextField()),
                ('benifit', models.CharField(max_length=1000)),
                ('price', models.IntegerField(blank=True)),
                ('image', models.ImageField(default='deafault.jpeg', upload_to='poojatype')),
            ],
        ),
    ]
