# Generated by Django 4.2.4 on 2023-08-31 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('astro', '0003_pooja'),
    ]

    operations = [
        migrations.CreateModel(
            name='PujaForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userName', models.CharField(max_length=100)),
                ('mail', models.EmailField(max_length=254)),
                ('phoneNo', models.CharField(max_length=10)),
                ('selectedDate', models.DateField()),
                ('selectedTime', models.TimeField()),
                ('puja_id', models.IntegerField()),
            ],
        ),
    ]
